ROSTemplateFormatVersion: '2015-09-01'
Parameters:
  RepoType:
    Type: String
    Label:
      en: Repository type
      zh-cn: 仓库类型
    AllowedValues:
      - Public
      - Private
    Default: Public
    AssociationPropertyMetadata:
      ValueLabelMapping:
        Public: 公开
        Private: 私有
  PublicGitRepoUrl:
    Type: String
    Label:
      zh-cn: Git Clone URL
      en: Git Clone Web URL
    Description:
      zh-cn: Git clone地址，https格式
      en: Git clone address in https format
    AssociationPropertyMetadata:
      Visible:
        Condition:
          'Fn::Equals':
            - '${RepoType}'
            - 'Public'
    # 需要允许默认空值，这样CommitHash的AssociationProperty可以识别出用RepoUrl还是其他参数
    AllowedPattern: '^(https:\/\/[^\s]+\.git)?$'
    Default: https://gitee.com/aliyun-computenest/springboot-demo.git
  Platform:
    Type: String
    Label:
      en: Git platform
      zh-cn: Git平台
    Default: github
    AllowedValues:
      - gitee
      - github
    AssociationProperty: ALIYUN::OOS::GitPlatform::Name
    AssociationPropertyMetadata:
      Visible:
        Condition:
          'Fn::Equals':
            - '${RepoType}'
            - 'Private'
  Owner:
    Type: String
    Label:
      en: Owner
      zh-cn: 所有者
    AssociationProperty: ALIYUN::OOS::GitAccount::Name
    AssociationPropertyMetadata:
      Platform: '${Platform}'
      Visible:
        Condition:
          'Fn::Equals':
            - '${RepoType}'
            - 'Private'
    Default: ''
  Organization:
    Type: String
    Label:
      en: Organization (optional)
      zh-cn: 组织（可选）
    Description:
      en: No need for user own repository
      zh-cn: 个人仓库无需选择
    Default: ''
    AssociationProperty: ALIYUN::OOS::GitOrganization::Name
    AssociationPropertyMetadata:
      Platform: ${Platform}
      Owner: ${Owner}
      Visible:
        Condition:
          'Fn::Equals':
            - '${RepoType}'
            - 'Private'
  Repository:
    Type: String
    Label:
      en: Repository
      zh-cn: 仓库
    AssociationProperty: ALIYUN::OOS::GitRepository::Name
    AssociationPropertyMetadata:
      Platform: '${Platform}'
      Owner: '${Owner}'
      Organization: ${Organization}
      Visible:
        Condition:
          'Fn::Equals':
            - '${RepoType}'
            - 'Private'
    Default: ''
Metadata:
  'ALIYUN::ROS::Interface':
    ParameterGroups:
      - Parameters:
          - RepoType
          - PublicGitRepoUrl
          - Platform
          - Owner
          - Organization
          - Repository
        Label:
          default:
            en: Application source
            zh-cn: 应用来源