ROSTemplateFormatVersion: '2015-09-01'
Parameters:
  Platform:
    Type: String
    Label:
      en: Git platform
      zh-cn: Git平台
    Default: github
    AllowedValues:
      - gitee
      - github
    AssociationProperty: ALIYUN::OOS::GitPlatform::Name
  Owner:
    Type: String
    Label:
      en: Git platform account
      zh-cn: Git平台账户
    AssociationProperty: ALIYUN::OOS::GitAccount::Name
    AssociationPropertyMetadata:
      Platform: '${Platform}'
  RepoType:
    Type: String
    Label:
      en: Repository type
      zh-cn: 仓库类型
    AllowedValues:
      - Public
      - Private
    Default: Public
    AssociationPropertyMetadata:
      ValueLabelMapping:
        Public: 公开仓库
        Private: 个人或组织的私有仓库
  PublicGitRepoUrl:
    Type: String
    Label:
      zh-cn: Git Clone地址（https）
      en: Git Clone URL(https)
    Description:
      en: 
      zh-cn: |-
        示例项目<ul>
        <li><a href="https://gitee.com/aliyun-computenest/java-springboot-demo" target="_blank">Java SpringBoot</a>: https://gitee.com/aliyun-computenest/java-springboot-demo.git</li>
        <li><a href="https://gitee.com/aliyun-computenest/java-springboot-demo" target="_blank">Python示例</a>: https://gitee.com/aliyun-computenest/java-springboot-demo.git</li>
        <li><a href="https://gitee.com/aliyun-computenest/java-springboot-demo" target="_blank">Golang示例</a>: https://gitee.com/aliyun-computenest/java-springboot-demo.git</li>
        <li><a href="https://gitee.com/aliyun-computenest/java-springboot-demo" target="_blank">NodeJs示例</a>: https://gitee.com/aliyun-computenest/java-springboot-demo.git</li>
        <li><a href="https://gitee.com/aliyun-computenest/java-springboot-demo" target="_blank">Ruby示例</a>: https://gitee.com/aliyun-computenest/java-springboot-demo.git</li>
        </ul>
        热门开源项目推荐<ul>
        <li><a href="https://gitee.com/aliyun-computenest/java-springboot-demo" target="_blank">热门项目1</a>: https://gitee.com/aliyun-computenest/java-springboot-demo.git</li>
        <li><a href="https://gitee.com/aliyun-computenest/java-springboot-demo" target="_blank">热门项目2</a>: https://gitee.com/aliyun-computenest/java-springboot-demo.git</li>
        <li><a href="https://gitee.com/aliyun-computenest/java-springboot-demo" target="_blank">热门项目3</a>: https://gitee.com/aliyun-computenest/java-springboot-demo.git</li>
        <li><a href="https://gitee.com/aliyun-computenest/java-springboot-demo" target="_blank">热门项目4</a>: https://gitee.com/aliyun-computenest/java-springboot-demo.git</li>
        <li><a href="https://gitee.com/aliyun-computenest/java-springboot-demo" target="_blank">热门项目5</a>: https://gitee.com/aliyun-computenest/java-springboot-demo.git</li>
        </ul>
    AssociationPropertyMetadata:
      Visible:
        Condition:
          'Fn::Equals':
            - '${RepoType}'
            - 'Public'
    # 需要允许默认空值，这样CommitHash的AssociationProperty可以识别出用RepoUrl还是其他参数
    AllowedPattern: '^(https:\/\/[^\s]+\.git)?$'
    Default: https://gitee.com/aliyun-computenest/springboot-demo.git
  Organization:
    Type: String
    Label:
      en: Organization (optional)
      zh-cn: 组织（可选）
    Description:
      en: No need for user own repository
      zh-cn: 个人仓库无需选择
    Default: ''
    AssociationProperty: ALIYUN::OOS::GitOrganization::Name
    AssociationPropertyMetadata:
      Platform: ${Platform}
      Owner: ${Owner}
      Visible:
        Condition:
          'Fn::Equals':
            - '${RepoType}'
            - 'Private'
  Repository:
    Type: String
    Label:
      en: Repository
      zh-cn: 仓库
    AssociationProperty: ALIYUN::OOS::GitRepository::Name
    AssociationPropertyMetadata:
      Platform: '${Platform}'
      Owner: '${Owner}'
      Organization: ${Organization}
      Visible:
        Condition:
          'Fn::Equals':
            - '${RepoType}'
            - 'Private'
    Default: ''
Metadata:
  'ALIYUN::ROS::Interface':
    ParameterGroups:
      - Parameters:
          - Platform
          - Owner
          - RepoType
          - PublicGitRepoUrl
          - Organization
          - Repository
        Label:
          default:
            en: Application source
            zh-cn: 应用来源