Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      ArtifactRelation:
        'aliyun_3_x64_20G_alibase_20240819.vhd':
          ArtifactId: artifact-6312bbc1751943678574
          ArtifactVersion: 2
    TemplateConfigs:
      - Name: docker
        Url: 'ros_templates/template.yaml'
        AllowedRegions:
          - cn-hangzhou
          - cn-beijing
          - cn-shanghai
          - ap-southeast-1
          - cn-qingdao
          - cn-zhangjiakou
          - cn-huhehaote
          - cn-wulanchabu
          - cn-nanjing
          - cn-shenzhen
          - cn-heyuan
          - cn-guangzhou
          - cn-fuzhou
          - cn-wuhan-lr
          - cn-chengdu
          - cn-hongkong
          - ap-northeast-1
          - ap-northeast-2
          - ap-southeast-3
          - ap-southeast-6
          - ap-southeast-5
          - ap-southeast-7
          - us-east-1
          - us-west-1
          - eu-west-1
          - me-east-1
          - eu-central-1
  OperationMetadata:
    ModifyParametersConfig:
      - TemplateName: docker
        Operation:
          - Name: 更新应用程序
            Description: 从指定分支拉取更新，更新容器应用程序，需要重启应用进程
            Type: Custom
            Parameters:
              - Branch
              - ImagePullPath
              - AcrUsername
              - AcrPassword
          - Name: 修改容器环境变量
            Description: 修改容器环境变量，需要重启应用进程
            Type: Custom
            Parameters:
              - EnvVar
          - Name: 修改ECS实例配置
            Description: 修改ECS实例配置，可能会重启ECS实例
            Type: Custom
            Parameters:
              - Port
              - EcsInstanceType
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    Name: 单机容器应用
    ShortDescription: 从代码仓库部署单机容器应用
    Image: 'resources/icons/service_logo.png'
