Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata: {}
    TemplateConfigs:
      - Name: docker
        Url: 'ros_templates/template.yaml'
        AllowedRegions: []
  OperationMetadata:
    ModifyParametersConfig:
      - TemplateName: docker
        Operation:
          - Name: 更新应用程序
            Description: 从指定分支拉取最新代码，更新应用程序。分支的Commit无变化时不更新
            Type: Custom
            Parameters:
              - Branch
              - CommitHash
              - ImagePullPath
              - AcrUsername
              - AcrPassword
          - Name: 修改环境变量
            Description: 修改环境变量，将重启应用进程
            Type: Custom
            Parameters:
              - EnvVar
              - ImagePullPath
              - AcrUsername
              - AcrPassword
          - Name: 修改云服务器配置
            Description: 修改云服务器配置，可能需要重启服务器或应用进程
            Type: Custom
            Parameters:
              - Port
              - EcsInstanceType
              - InternetChargeType
              - InternetMaxBandwidthOut
              - ImagePullPath
              - AcrUsername
              - AcrPassword
  ServiceType: private
  ServiceInfo:
    - Locale: zh-CN
      Name: 从代码仓库部署容器应用单机版
      Image: 'resources/icons/service_logo.png'
    - Locale: en-US
      Name: Deploy Single Node Application From Git Repository
      Image: 'resources/icons/service_logo.png'

