Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata: {}
    TemplateConfigs:
      - Name: docker
        Url: 'ros_templates/template.yaml'
        AllowedRegions: []
  OperationMetadata:
    ModifyParametersConfig:
      - TemplateName: docker
        Operation:
          - Name: 更新应用程序
            Description: 从指定分支拉取最新代码，更新应用程序。分支的Commit无变化时不更新
            Type: Custom
            Parameters:
              - Branch
              - CommitHash
              - ImagePullPath
              - AcrUsername
              - AcrPassword
          - Name: 修改容器环境变量
            Description: 修改容器环境变量，需要重启应用
            Type: Custom
            Parameters:
              - EnvVar
              - ImagePullPath
              - AcrUsername
              - AcrPassword
          - Name: 修改ECS实例配置
            Description: 修改ECS实例配置，需要重启应用
            Type: Custom
            Parameters:
              - Port
              - EcsInstanceType
              - ImagePullPath
              - AcrUsername
              - AcrPassword
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    Name: 单机容器应用
    ShortDescription: 从代码仓库部署单机容器应用
    Image: 'resources/icons/service_logo.png'
