Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata: {}
    TemplateConfigs:
      - Name: docker
        Url: 'ros_templates/template.yaml'
        AllowedRegions: []
  OperationMetadata:
    ModifyParametersConfig:
      - TemplateName: docker
        Operation:
          - Name: Update Application Program
            Description: Pull the latest code from the specified branch to update the application. No update is performed if the branch's commits have no change.
            Type: Custom
            Parameters:
              - Branch
              - CommitHash
              - ImagePullPath
              - AcrUsername
              - AcrPassword
          - Name: Modify Environment Variables
            Description: Modify the environment variables, which will restart the application process.
            Type: Custom
            Parameters:
              - EnvVar
              - ImagePullPath
              - AcrUsername
              - AcrPassword
          - Name: Modify ECS instance Configuration
            Description: Modify the ECS instance configuration, which may require a server or application process restart.
            Type: Custom
            Parameters:
              - Port
              - EcsInstanceType
              - InternetChargeType
              - InternetMaxBandwidthOut
              - ImagePullPath
              - AcrUsername
              - AcrPassword
  ServiceType: private
  ServiceInfo:
    - Locale: zh-CN
      Name: 从代码仓库部署容器应用单机版
      Image: 'resources/icons/service_logo.png'
    - Locale: en-US
      Name: Deploy Single Node Application From Git Repository
      Image: 'resources/icons/service_logo.png'

