Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata: {}
    TemplateConfigs:
      - Name: docker
        Url: 'ros_templates/template.yaml'
        AllowedRegions: []
  OperationMetadata:
    ModifyParametersConfig:
      - TemplateName: docker
        Operation:
          - Name: 更新应用程序 | Update Application Program
            Description: 从指定分支拉取最新代码，更新应用程序。分支的Commit无变化时不更新 | Update application program, if the commit hash of the branch is not changed, the application will not be updated
            Type: Custom
            Parameters:
              - Branch
              - CommitHash
              - ImagePullPath
              - AcrUsername
              - AcrPassword
          - Name: 修改环境变量 | Modify Environment Variable
            Description: 修改环境变量，将重启应用进程 | Modify environment variable, application process will be restarted
            Type: Custom
            Parameters:
              - EnvVar
              - ImagePullPath
              - AcrUsername
              - AcrPassword
          - Name: 修改云服务器配置|Modify ECS Instance Configuration
            Description: 修改云服务器配置，可能需要重启服务器或应用进程 | Modify ECS instance configuration, may need to restart server or application process
            Type: Custom
            Parameters:
              - Port
              - EcsInstanceType
              - InternetChargeType
              - InternetMaxBandwidthOut
              - ImagePullPath
              - AcrUsername
              - AcrPassword
  ServiceType: private
  ServiceInfo:
    - Locale: zh-CN
      Name: 从代码仓库部署容器应用单机版
      Image: 'resources/icons/service_logo.png'
    - Locale: en-US
      Name: Deploy Single Node Application From Git Repository
      Image: 'resources/icons/service_logo.png'

